
name: Build on Ubuntu

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  build:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: ['3.11','3.12']

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - run: |
        curl -Lo mkn https://github.com/mkn/mkn/releases/download/latest/mkn_nix
        chmod +x mkn
        ./mkn clean build test run -p scope_timer,threaded_scope_timer -Oa "-fPIC -std=c++20" -W 9

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - run: |
        python3 -m pip install -r requirements.txt
        ./sh/lint.sh
        export PATH="$PWD:$PATH"
        ./sh/test.sh
