
name: Build on Ubuntu

on:
  pull_request:

jobs:
  build:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: ['3.8', '3.9','3.10', '3.11']
        os: [ubuntu-20.04] #, macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - run: ./sh/test.sh

