name: Production Builds
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: ['3.11']
        os: [ubuntu-latest]

    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
        run: |
          python3 -m pip install build twine pip --upgrade
          python3 -m build
          python3 -m twine check dist/*
          python3 -m twine upload --repository testpypi --skip-existing dist/*
